version: "3.9"

services:
  trainer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: grokking_trainer
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ~/Work/Grokking-Instability-Analysis/src:/workspace/src
      - ~/Work/Grokking-Instability-Analysis/experiments:/workspace/experiments
      - ~/Work/Grokking-Instability-Analysis/configs:/workspace/configs
      - ~/Work/Grokking-Instability-Analysis/checkpoints:/workspace/checkpoints
      - ~/Work/Grokking-Instability-Analysis/data:/workspace/data
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace
      - WANDB_MODE=offline
